#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Nov 22 02:31:54 WET 2023
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim top_level_tb_behav -key {Behavioral:sim_1:Functional:top_level_tb} -tclbatch top_level_tb.tcl -view /home/francisco/Desktop/Vivado/VeSPA/top_level_tb_behav.wcfg -view /home/francisco/Desktop/Vivado/VeSPA/datapath_tb_behav.wcfg -log simulate.log"
xsim top_level_tb_behav -key {Behavioral:sim_1:Functional:top_level_tb} -tclbatch top_level_tb.tcl -view /home/francisco/Desktop/Vivado/VeSPA/top_level_tb_behav.wcfg -view /home/francisco/Desktop/Vivado/VeSPA/datapath_tb_behav.wcfg -log simulate.log

