set_property IOSTANDARD LVCMOS33 [get_ports i_Clk]
set_property IOSTANDARD LVCMOS33 [get_ports i_Rst]
set_property PACKAGE_PIN T14 [get_ports i_Clk]
set_property PACKAGE_PIN K18 [get_ports i_Rst]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets i_Clk_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports {o_Output[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Output[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Output[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Output[0]}]
set_property PACKAGE_PIN D18 [get_ports {o_Output[3]}]
set_property PACKAGE_PIN G14 [get_ports {o_Output[2]}]
set_property PACKAGE_PIN M15 [get_ports {o_Output[1]}]
set_property PACKAGE_PIN M14 [get_ports {o_Output[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {i_IntLines[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_IntLines[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_IntLines[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_IntLines[0]}]
